export const route = '/';
export const heroContent = '.hero-content';
export const heroCvButton = '.hero a[href="/cv"]';
export const heroContactButton = '.hero a[href="/contacto"]';
export const quickIntroHeader = '.quick-intro-header';
export const introStats = '.intro-stats';
export const statCards = '.stat-card';
export const portfolioContext = '.portfolio-context, .intro-highlights';
export const currentFocus = '.current-focus';
export const stackVisual = '.stack-visual';
export const stackItemExpandable = '.stack-item--expandable';
export const stackItemOpen = '.stack-item--expandable.is-open';
export const stackDescriptionRevealed = '.stack-description.is-revealed';
export const akkodisLink = '.current-focus a[href*="akkodis.com"]';
export const elConfidencialLink = '.current-focus a[href*="elconfidencial.com"]';
export const publicRepoLink = 'a[href*="portfolio-public"]';
export const publicRepoUrl = 'https://github.com/joseguillermomoreu-gif/portfolio-public';
export const akkodisUrl = 'https://www.akkodis.com';
export const elConfidencialUrl = 'https://www.elconfidencial.com';
