export const heading = 'h1';
export const pdfLink = 'a[href*=".pdf"]';
export const programmingCounter = '.programming-counter';
export const wipButton = '.cv-generator-btn';
export const cvPage = '.cv-page';
export const cvHeader = '.cv-header';
export const pdfDownloadCard = '.pdf-download-card';
export const cvTechInfo = '.cv-tech-info';
export const skillsCarouselSection = '.skills-carousel-section';
