export const route = '/proyectos';
export const heading = 'h1';
export const projectCards = '[data-testid="project-card"]';
export const projectToggle = '[data-testid="project-toggle"]';
export const projectName = '[data-testid="project-name"]';
export const projectStatus = '[data-testid="project-status"]';
export const projectDetails = '[data-testid="project-details"]';
export const projectHighlights = '[data-testid="project-highlights"]';
export const projectGithubLink = '[data-testid="project-github-link"]';
export const projectWebsiteLink = '[data-testid="project-website-link"]';
export const projectsHeader = '.projects-header';
export const projectsFooter = '.projects-footer';
export const donationSection = '[data-testid="donation-section"]';
export const donationLink = '[data-testid="donation-link"]';
export const donationModal = '[data-testid="donation-modal"]';
export const donationQrImage = '[data-testid="donation-qr-image"]';
export const donationPaypalLink = '[data-testid="donation-paypal-link"]';
export const donationModalClose = '.donation-modal-close';

export const ppiaProjectName = 'PPIA';
export const ppiaStatusPrivate = 'Private';
export const ppiaHighlightText = 'producción interna';
