export const HomeSelectors = {
  hero: '.hero',
  heroContent: '.hero-content',
  heroName: '.hero h1, .hero-name',
  heroCvButton: '.hero a[href="/cv"]',
  heroContactButton: '.hero a[href="/contacto"]',
  quickIntro: '.quick-intro',
  quickIntroHeader: '.quick-intro-header',
  introStats: '.intro-stats',
  statCards: '.stat-card',
  portfolioContext: '.portfolio-context, .intro-highlights',
  currentFocus: '.current-focus',
  skillsSection: '.skills-section',
  stackVisual: '.stack-visual',
  stackItems: '.stack-item',
  akkodisLink: 'a[href*="akkodis.com"]',
  elConfidencialLink: 'a[href*="elconfidencial.com"]',
  githubProfileLink: 'a[href="https://github.com/joseguillermomoreu-gif"]',
} as const;
